// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var container = {
  display: "flex",
  fontFamily: "sans-serif",
  alignItems: "center",
  justifyContent: "center"
};

var Styles = /* module */[/* container */container];

function App(Props) {
  var message = Props.message;
  var match = React.useState((function () {
          return false;
        }));
  var setMessageVisible = match[1];
  var handleClick = function (_event) {
    return Curry._1(setMessageVisible, (function (messageVisible) {
                  return !messageVisible;
                }));
  };
  return React.createElement("div", {
              style: container
            }, React.createElement("h1", {
                  onClick: handleClick
                }, match[0] ? message : "Click me!"));
}

var make = App;

exports.Styles = Styles;
exports.make = make;
/* react Not a pure module */
